
options(shiny.maxRequestSize=2000*1024^2)


######## 3D printing app #########


### Define UI ----
ui <- dashboardPage(
  dashboardHeader(title = "MAsP"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Homepage", tabName = "Homepage", icon = icon("home")),
      menuItem("Distribution Map", tabName = "DistributionPlot", icon = icon("edit")),
      menuItem("Pattern Discovery/Extraction", tabName = "Process", icon = icon("edit"))

    )
  ),
  dashboardBody(
    tags$head(
      tags$style(
        "body{
          height: auto;
          margin: auto;
}"
      )
    ),

    tabItems(
      ##Homepage
      {
        tabItem(tabName = "Homepage",
                fluidPage(
                  titlePanel(strong("MAsP")),
                  mainPanel(
                    img(src="logo.png",height=120,width=120),
                    h4(strong("MAsP is a R Shiny-based interactive application designed for visualization and pattern extraction of spatial quantitative proteomics data generated by Micro-scaffold Assisted Spatial Proteomics (MASP)")),
                    h4("Fundamental components of MAsP include:"),
                    h4(icon("check"),"Plotting of protein abundance distribution"),
                    h4(icon("check"),"Filtering of protein abundance distribution"),
                    h4(icon("check"),"Similarity discovery of protein abundance distribution based on protein abundance distribution correlation"),
                    h4(icon("check"),"Protein clustering"),
                    h4("Click the button below to download the manual:"),
                    downloadButton("downloadManual", label="Download Manual", icon=icon("download")),
                    h4("For any questions, suggestions, and other relevant topics about UHR-IonStar, please contact the developers:"),
                    h4("Shuo Qian:",
                       "sqian@buffalo.edu"),
                    h4("Min Ma:",
                       "minma@buffalo.edu"),
                    h4("Shihan Huo:",
                       "shihanhu@buffalo.edu"),
                    h4("Jun Qu:",
                       "junqu@buffalo.edu")
                  )
                )
        )},
      ## Distrubution plot
      {
        tabItem(tabName = "DistributionPlot",
                fluidPage(
                  titlePanel(strong("Distribution Map")),
                  sidebarLayout(
                    position = "right",
                    sidebarPanel(
                      h4(strong("Data Upload")),
                      fileInput("ProteinData", "Upload quantitative file (.csv):",
                                accept=".csv"),
                      fileInput("Locations", "Upload location information (.csv):",
                                accept=".csv"),
                      fileInput("BrainCover", "Upload tissue shape template (.png):",
                                accept=c(".png")),
                      textInput(inputId = "TargetProtein",
                                label = "Input the name of protein you would like to illustrate:"),
                      checkboxInput("Scale",
                                    "Convert data to Z-score", value = TRUE),
                      checkboxInput("Mask",
                                    "Add tissue shape template"),
                      checkboxInput("Transparent",
                                    "Make the plot with transparent background while downloading"),
                      checkboxInput("Legend",
                                    "Plot with legend", value = TRUE),
                      radioButtons("Limit","Choose the range of map color display:",
                                   c("No limit"="none",
                                     "Inter-quantile range"="outlierRM",
                                     "Customized" = "customized")),
                      textInput(inputId = "upperl",
                                label = "Input the upper bound for protein values (if customized):", value = "2"),
                      textInput(inputId = "lowerl",
                                label = "Input the lower bound for protein values (if customized):", value = "-2"),
                      textInput(inputId = "Color3",
                                label = "Input the upper color for the distribution map:", value = "#FF0000"),
                      textInput(inputId = "Color2",
                                label = "Input the middle color for the distribution map:", value = "#FFFF00"),
                      textInput(inputId = "Color1",
                                label = "Input the lower color for the distribution map:", value = "#00FF00"),
                      actionButton(inputId = "PreGoButton",label = "Draw Distribution Map",icon=icon("pencil"),width="100%"),

                      p(strong("Map saving options:")),
                      sliderInput("sliderwid","Global plot width (inches):",
                                  min = 4,max = 20,value = 8),
                      sliderInput("sliderhei","Global plot height (inches):",
                                  min = 4,max = 20,value = 6),
                      downloadButton("SingleDownload", label="Download current map", icon=icon("download")),
                      tags$hr(),
                      h4(strong("Batch mode")),
                      fileInput("ProteinList", "Upload a list containing protein names (.csv)",
                                accept=".csv"),
                      br(),
                      br(),
                      verbatimTextOutput("output_folder", placeholder = TRUE),
                      actionButton("output_folder", "Select the Output Folder",icon=icon("upload"),width="100%"),
                      br(),
                      br(),
                      helpText('Plot settings are inherited from the previous settings, or user can change them before plotting.',
                               style = 'color:blue'),
                      actionButton(inputId = "BatchDownload",label = "Generate Selected Distribution Maps",icon=icon("pencil"),width="100%"),


                    ),#sidebarpanel
                    mainPanel(
                      tags$hr(),
                      h3(strong("Location Preview")),
                      plotOutput("Preview",height = '600px'),
                      #plotOutput("Preview", width = '800px',height = '600px'),
                      tags$hr(),
                      h3(strong("Protein Distribution Map")),
                      plotOutput("DistriPlot",height = '600px')
                      #plotOutput("DistriPlot", width = '800px',height = '600px')
                    )
                  )#sidebarlayout
                )#fieldpage
        )}, # tabItem
      {
        tabItem(tabName = "Process",
                fluidPage(
                  titlePanel(strong("Pattern Discovery/Extraction")),
                  sidebarLayout(
                    position = "right",
                    sidebarPanel(
                      h4(strong("Find proteins with pattern by the first value of variance explained (VE) in singular value decomposition (SVD)")),
                      br(),
                      br(),
                      actionButton("SVDgoButton", "Perform Singular Value Decomposition on the Protein Quantitative file",
                                   icon=icon("pencil"),width="100%"),
                      helpText('Missing values will be forcely imputated because SVD requires missing data free.', style = 'color:blue'),
                      downloadButton("df_impu", label="Download imputated dataset", icon=icon("download")),
                      downloadButton("VE_download", label="Download VE rank plot", icon=icon("download")),
                      br(),
                      br(),
                      radioButtons("VEcutoff","Set the threshold of VE value:",
                                   c("Median"="med",
                                     "Customized" = "customized")),
                      textInput(inputId = "VEcutoffsetting",
                                label = "Input the customized VE cutoff value:", value = "0.3"),
                      downloadButton("VE_filtered_download", label="Download VE filtered protein dataset", icon=icon("download")),
                      tags$hr(),
                      br(),
                      br(),
                      h4(strong("Spectral Clustering on filtered proteins")),
                      actionButton("SCgoButton", "Perform Spectral Clustering on SVD-filtered protein file",
                                   icon=icon("pencil"),width="100%"),
                      downloadButton("df_SC", label="Download protein file with clustering labels", icon=icon("download")),
                      downloadButton("SCPCA_download", label="Download PCA plot grouped by clustering labels", icon=icon("download")),
                      br(),
                      br(),
                      tags$hr(),
                      h4(strong("Find proteins with similar distribution comparing to the target protein")),
                      textInput("TargetPro", "Input a name of protein:"),
                      radioButtons("CorrType","Select the correlation type:",
                                   c("Pearson Correlation"="pearson",
                                     "Cosine Similarity" = "cosine")),
                      br(),
                      br(),
                      actionButton(inputId = "CorrGoButton",label = "Find correlations",icon=icon("pencil"),width="100%"),
                      br(),
                      br(),
                      downloadButton("corrdata_download", label="Download correlation rank data", icon=icon("download")),
                      downloadButton("corrplot_download", label="Download correlation rank plot", icon=icon("download")),

                    ),#sidebarpanel
                    mainPanel(
                      h3(strong("Plot Area")),
                      br(),
                      br(),
                      h4(strong("VE Rank Plot")),
                      plotOutput("VEplot",height = '600px'),
                      br(),
                      br(),
                      h4(strong("PCA Plot with Labels from Spectral Clustering")),
                      plotOutput("SCPCAPlot",height = '600px'),
                      br(),
                      br(),
                      h4(strong("Correlation Rank Plot")),
                      plotOutput("CorrPlot",height = '600px'),
                      br(),
                      br(),
                      h4(strong("TOP3 Correlated Proteins")),
                      plotOutput('TOP_plot', height = '600px')
                    )
                  )#sidebarlayout
                )#fieldpage
        )} # tabItem



    ) # tabItems
  ) #dashboardBody
) #dashboardPage




### Define server logic ----
server <- function(input, output, session) {

  output$downloadManual <- downloadHandler(
    filename <- function(){
      paste("MAsP_Manual","pdf",sep = ".")
    },

    content <- function(file){
      file.copy("Manual.pdf",file)
    },
    contentType = "application/pdf"
  )

  #### Panel 1 DistributionPlot ####
  ## upload data ##

  # quantitative data

  df <- reactive({
    req(input$ProteinData)
    ext <- tools::file_ext(input$ProteinData$name)
    read.csv(input$ProteinData$datapath, row.names = 1)
  })
  # location info
  location <- reactive({
    req(input$Locations)
    ext <- tools::file_ext(input$Locations$name)
    read.csv(input$Locations$datapath, row.names = 1)
  })

  cover <- reactive({
    req(input$BrainCover)
    ext <- tools::file_ext(input$BrainCover$name)
    tmp <- readPNG(input$BrainCover$datapath)
    rasterGrob(tmp, interpolate = TRUE)
  })

  output$Preview <- renderPlot({
    MyPreview(location())
  })

  test <- eventReactive(input$PreGoButton,{
    MyDistriPlot(df = df(),location = location(), target_name = input$TargetProtein, limit = input$Limit, scale = input$Scale, upperL = input$upperl, lowerL = input$lowerl,
                 mask = input$Mask, color1 = input$Color1, color2 = input$Color2, color3 = input$Color3,
                 transparent = input$Transparent, Legend = input$Legend, g = cover())
  })

  output$DistriPlot <- renderPlot({
    test()
  })

  output$SingleDownload <- downloadHandler(
    filename = function() {
      paste('Plot-', gsub(" ","-",date()),'.png', sep='')
    },
    content = function(con) {
      device <- function(..., width, height) grDevices::png(..., width = input$sliderwid, height = input$sliderhei, res = 300, units = "in")
      ggsave(con, plot=test(),device = device)
    }
  )
  # batch output
  Protein_List <- reactive({
    req(input$ProteinList)
    ext <- tools::file_ext(input$ProteinList$name)
    switch(ext,
           csv = read.csv(input$ProteinList$datapath, header = FALSE),
           tsv = read.csv(input$ProteinList$datapath, sep="\t",fileEncoding="windows-1252", header = FALSE),
           validate("Invalid file; Please upload a .csv or .tsv file")
    )
  })

  global_output_folder <- reactiveValues(datapath = getwd())

  output_folder <- reactive({
    return(parseDirPath(volumes, input$output_folder))
  })

  output$output_folder <- renderText({
    global_output_folder$datapath
  })

  observeEvent(input$output_folder, {

    if(Sys.info()["sysname"] != "Darwin")
    {
      selected_folder <- rchoose.dir(caption = "Choose output folder",default = "~")
    }else
    {
      selected_folder <- tcltk::tk_choose.dir(caption = "Choose output folder",default = "~")
    }
    if(length(selected_folder)>0)
    {
      if(!is.na(selected_folder))
      {
        selected_folder <- gsub("\\\\","/",selected_folder)
        global_output_folder$datapath <- paste0(selected_folder,"/")
      }
    }
  })

  observeEvent(input$BatchDownload,{
    MyDistriPlot_batch(df = df(),location = location(), proteins_csv = Protein_List(), directory = global_output_folder$datapath, limit = input$Limit,
                       scale = input$Scale, upperL = input$upperl, lowerL = input$lowerl, mask = input$Mask, Legend = input$Legend,
                       color1 = input$Color1, color2 = input$Color2, color3 = input$Color3,
                       transparent = input$Transparent, width = input$sliderwid, height = input$sliderhei, g = cover())
  })


  #### Panel 2 Pattern Recognition ####
  test2 <- eventReactive(input$SVDgoButton,{
    SVD_plot(df = df(), location = location())
  })
  output$VEplot <- renderPlot({
    test2()$VE_plot
  })
  output$df_impu <- downloadHandler(
    filename = function() {
      paste('Imputated_data-', gsub(" ","-",date()), '.csv', sep='')
    },
    content = function(con) {
      write.csv(test2()$df_impu, con)
    }
  )
  output$VE_download <- downloadHandler(
    filename = function() {
      paste('VE-Plot-', gsub(" ","-",date()),'.png', sep='')
    },
    content = function(con) {
      device <- function(..., width, height) grDevices::png(..., width = input$sliderwid, height = input$sliderhei, res = 300, units = "in")
      ggsave(con, plot=test2()$VE_plot,device = device)
    }
  )

  tmp <- reactive({VE_filtering(test2()$VE_results, input$VEcutoff, input$VEcutoffsetting)})
  df_filtered <- reactive({test2()$df_impu[tmp(),]})
  output$VE_filtered_download <- downloadHandler(

    filename = function() {
      paste('Filtered_data-', gsub(" ","-",date()), '.csv', sep='')
    },
    content = function(con) {
      write.csv(df_filtered(), con)
    }
  )

  # spectral clustering
  test4 <- eventReactive(input$SCgoButton,{
    SClustering(df_filtered = df_filtered())
  })
  output$SCPCAPlot <- renderPlot({
    test4()$PCA_plot
  })
  output$SCPCA_download <- downloadHandler(
    filename = function() {
      paste('SCPCA-Plot-', gsub(" ","-",date()),'.png', sep='')
    },
    content = function(con) {
      device <- function(..., width, height) grDevices::png(..., width = input$sliderwid, height = input$sliderhei, res = 300, units = "in")
      ggsave(con, plot=test4()$PCA_plot,device = device)
    }
  )

  output$df_SC <- downloadHandler(
    filename = function() {
      paste('SC_labelled_data-', gsub(" ","-",date()), '.csv', sep='')
    },
    content = function(con) {
      write.csv(test4()$df_label, con)
    }
  )



  # correlation
  test3 <- eventReactive(input$CorrGoButton,{
    correlation_plot(df = df(), target_name = input$TargetPro, type = input$CorrType, location = location(), limit = input$Limit,
                     upperL = input$upperl, lowerL = input$lowerl, mask = input$Mask, color1 = input$Color1, color2 = input$Color2, color3 = input$Color3,
                     transparent = input$Transparent, g = cover())
  })

  output$CorrPlot <- renderPlot({
    test3()$corr_plot
  })

  output$TOP_plot <- renderPlot({
    grid.arrange(test3()$total_plots[[1]],test3()$total_plots[[2]],test3()$total_plots[[3]],test3()$total_plots[[4]], nrow = 2)
  })

  output$corrdata_download <- downloadHandler(
    filename = function() {
      paste('Corr_data-', gsub(" ","-",date()), '.csv', sep='')
    },
    content = function(con) {
      write.csv(test3()$corr_data, row.names = FALSE, con)
    }
  )
  output$corrplot_download <- downloadHandler(
    filename = function() {
      paste('Corr-Plot-', gsub(" ","-",date()),'.png', sep='')
    },
    content = function(con) {
      device <- function(..., width, height) grDevices::png(..., width = input$sliderwid, height = input$sliderhei, res = 300, units = "in")
      ggsave(con, plot=test3()$corr_plot,device = device)
    }
  )
}

# Run the application
shinyApp(ui = ui, server = server)



